<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ros_car_cmd</name>
  <version>0.0.0</version>
  <description>Autonomous navigation (waypoints + obstacle avoidance) for the CarROS car</description>
  <maintainer email="antonio.garofalo125@gmail.com">ros</maintainer>
  <license>GPLv3</license>
  <author email="antonio.garofalo125@gmail.com">Antonio Garofalo</author>
  <url type="website">https://github.com/Endless077</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>rclcpp</depend>
  <depend>ros_car_msgs</depend>
  <depend>std_srvs</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>